---
apiVersion: v1
kind: Service
metadata:
  name: pihole-sv
  namespace: dns-resolver
spec:
  selector:
    app: pihole
  ports:
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: pihole-dashboard
      port: 80
      targetPort: 80
  type: LoadBalancer

---
kind: Service
apiVersion: v1
metadata:
  name: unbound-sv
  namespace: dns-resolver
spec:
  selector:
    app: unbound
  clusterIP: 10.43.0.20
  ports:
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP
