---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/renovate/

patches:
  - target:
      kind: CronJob
      name: renovate-bot
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/image
        value: docker.io/renovate/renovate:42.40.3@sha256:db25edd077eeda3b0cba0ee0a0c103ff49e6ba4dfd69eddb44f7fcdc0503eae1
