---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/renovate/

patches:
  - target:
      kind: CronJob
      name: renovate-bot
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/image
        value: docker.io/renovate/renovate:42.13.3@sha256:5cdea7e2aadccbfe7fcf3451a53d037a27bc5463be4231b6109e10a2ab822a40
