---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/renovate/

patches:
  - target:
      kind: CronJob
      name: renovate-bot
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/image
        value: docker.io/renovate/renovate:42.29.5@sha256:2c98a157aa718e22c446df87a2554e141004ef7d5a638d71fa0c8712d1598706
