---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/core/valkey/

patches:
  - target:
      kind: Deployment
      name: valkey
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/image
        value: docker.io/valkey/valkey:9.0.0-alpine@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b
